// This file is auto-generated by @hey-api/openapi-ts

export const $Song = {
    required: ['albums', 'artists', 'duration', 'genres', 'release_date', 'title'],
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        producer: {
            type: 'string'
        },
        duration: {
            type: 'integer',
            format: 'int32'
        },
        release_date: {
            type: 'string',
            format: 'date-time'
        },
        albums: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        artists: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        genres: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const $Genre = {
    required: ['name'],
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const $Artist = {
    required: ['name', 'variant'],
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        variant: {
            type: 'string',
            enum: ['SINGER', 'RAPPER', 'BAND']
        }
    }
} as const;

export const $Album = {
    required: ['release_date', 'title'],
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        release_date: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;