// This file is auto-generated by @hey-api/openapi-ts

export type Song = {
    id?: string;
    title: string;
    producer?: string;
    duration: number;
    release_date: string;
    albums: Array<(string)>;
    artists: Array<(string)>;
    genres: Array<(string)>;
};

export type Genre = {
    id?: string;
    name: string;
};

export type Artist = {
    id?: string;
    name: string;
    variant: 'SINGER' | 'RAPPER' | 'BAND';
};

export type variant = 'SINGER' | 'RAPPER' | 'BAND';

export type Album = {
    id?: string;
    title: string;
    release_date: string;
};

export type ReadSongsResponse = Array<Song>;

export type ReadSongsError = unknown;

export type UpdateSongData = {
    body: Song;
};

export type UpdateSongResponse = Song;

export type UpdateSongError = unknown;

export type CreateSongData = {
    body: Song;
};

export type CreateSongResponse = Song;

export type CreateSongError = unknown;

export type ReadGenresResponse = Array<Genre>;

export type ReadGenresError = unknown;

export type UpdateGenreData = {
    body: Genre;
};

export type UpdateGenreResponse = Genre;

export type UpdateGenreError = unknown;

export type CreateGenreData = {
    body: Genre;
};

export type CreateGenreResponse = Genre;

export type CreateGenreError = unknown;

export type UpdatePostData = {
    body: Artist;
};

export type UpdatePostResponse = Artist;

export type UpdatePostError = unknown;

export type UpdateAlbumData = {
    body: Album;
};

export type UpdateAlbumResponse = Album;

export type UpdateAlbumError = unknown;

export type ServeSongCoverData = {
    path: {
        id: string;
    };
};

export type ServeSongCoverResponse = unknown;

export type ServeSongCoverError = unknown;

export type HandleSongCoverUploadData = {
    path: {
        id: number;
    };
};

export type HandleSongCoverUploadResponse = string;

export type HandleSongCoverUploadError = unknown;

export type ServeSongAudioData = {
    path: {
        id: string;
    };
};

export type ServeSongAudioResponse = unknown;

export type ServeSongAudioError = unknown;

export type HandleSongAudioUploadData = {
    path: {
        id: number;
    };
};

export type HandleSongAudioUploadResponse = string;

export type HandleSongAudioUploadError = unknown;

export type ServeArtistProfileData = {
    path: {
        id: string;
    };
};

export type ServeArtistProfileResponse = unknown;

export type ServeArtistProfileError = unknown;

export type HandleArtistProfileUploadData = {
    path: {
        id: number;
    };
};

export type HandleArtistProfileUploadResponse = string;

export type HandleArtistProfileUploadError = unknown;

export type ServeAlbumCoverData = {
    path: {
        id: string;
    };
};

export type ServeAlbumCoverResponse = unknown;

export type ServeAlbumCoverError = unknown;

export type HandleAlbumCoverUploadData = {
    path: {
        id: number;
    };
};

export type HandleAlbumCoverUploadResponse = string;

export type HandleAlbumCoverUploadError = unknown;

export type ReadArtistsResponse = Array<Artist>;

export type ReadArtistsError = unknown;

export type CreateArtistData = {
    body: Artist;
};

export type CreateArtistResponse = Artist;

export type CreateArtistError = unknown;

export type ReadAlbumsResponse = Array<Album>;

export type ReadAlbumsError = unknown;

export type CreateAlbumData = {
    body: Album;
};

export type CreateAlbumResponse = Album;

export type CreateAlbumError = unknown;

export type ReadSongData = {
    path: {
        id: string;
    };
};

export type ReadSongResponse = Song;

export type ReadSongError = unknown;

export type DeleteSongData = {
    path: {
        id: string;
    };
};

export type DeleteSongResponse = unknown;

export type DeleteSongError = unknown;

export type RecommendationsBasedOnSongData = {
    path: {
        id: string;
    };
};

export type RecommendationsBasedOnSongResponse = Array<Song>;

export type RecommendationsBasedOnSongError = unknown;

export type ReadSongsOfGenreData = {
    path: {
        id: string;
    };
};

export type ReadSongsOfGenreResponse = Array<Song>;

export type ReadSongsOfGenreError = unknown;

export type ReadSongsOfArtistData = {
    path: {
        id: string;
    };
};

export type ReadSongsOfArtistResponse = Array<Song>;

export type ReadSongsOfArtistError = unknown;

export type ReadGenreData = {
    path: {
        id: string;
    };
};

export type ReadGenreResponse = Genre;

export type ReadGenreError = unknown;

export type DeleteGenreData = {
    path: {
        id: string;
    };
};

export type DeleteGenreResponse = unknown;

export type DeleteGenreError = unknown;

export type ReadArtistData = {
    path: {
        id: string;
    };
};

export type ReadArtistResponse = Artist;

export type ReadArtistError = unknown;

export type ReadAlbumData = {
    path: {
        id: string;
    };
};

export type ReadAlbumResponse = Album;

export type ReadAlbumError = unknown;

export type DeleteSong1Data = {
    path: {
        id: string;
    };
};

export type DeleteSong1Response = unknown;

export type DeleteSong1Error = unknown;

export type DeleteAlbumData = {
    path: {
        id: string;
    };
};

export type DeleteAlbumResponse = unknown;

export type DeleteAlbumError = unknown;

export type $OpenApiTs = {
    '/songs': {
        get: {
            res: {
                /**
                 * OK
                 */
                '200': Array<Song>;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
        put: {
            req: UpdateSongData;
            res: {
                /**
                 * OK
                 */
                '200': Song;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
        post: {
            req: CreateSongData;
            res: {
                /**
                 * OK
                 */
                '200': Song;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/genres': {
        get: {
            res: {
                /**
                 * OK
                 */
                '200': Array<Genre>;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
        put: {
            req: UpdateGenreData;
            res: {
                /**
                 * OK
                 */
                '200': Genre;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
        post: {
            req: CreateGenreData;
            res: {
                /**
                 * OK
                 */
                '200': Genre;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/artist': {
        put: {
            req: UpdatePostData;
            res: {
                /**
                 * OK
                 */
                '200': Artist;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/album': {
        put: {
            req: UpdateAlbumData;
            res: {
                /**
                 * OK
                 */
                '200': Album;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/files/song/cover/{id}': {
        get: {
            req: ServeSongCoverData;
            res: {
                /**
                 * OK
                 */
                '200': unknown;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
        post: {
            req: HandleSongCoverUploadData;
            res: {
                /**
                 * OK
                 */
                '200': string;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/files/song/audio/{id}': {
        get: {
            req: ServeSongAudioData;
            res: {
                /**
                 * OK
                 */
                '200': unknown;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
        post: {
            req: HandleSongAudioUploadData;
            res: {
                /**
                 * OK
                 */
                '200': string;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/files/artist/profile/{id}': {
        get: {
            req: ServeArtistProfileData;
            res: {
                /**
                 * OK
                 */
                '200': unknown;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
        post: {
            req: HandleArtistProfileUploadData;
            res: {
                /**
                 * OK
                 */
                '200': string;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/files/album/cover/{id}': {
        get: {
            req: ServeAlbumCoverData;
            res: {
                /**
                 * OK
                 */
                '200': unknown;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
        post: {
            req: HandleAlbumCoverUploadData;
            res: {
                /**
                 * OK
                 */
                '200': string;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/artists': {
        get: {
            res: {
                /**
                 * OK
                 */
                '200': Array<Artist>;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
        post: {
            req: CreateArtistData;
            res: {
                /**
                 * OK
                 */
                '200': Artist;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/albums': {
        get: {
            res: {
                /**
                 * OK
                 */
                '200': Array<Album>;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
        post: {
            req: CreateAlbumData;
            res: {
                /**
                 * OK
                 */
                '200': Album;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/songs/{id}': {
        get: {
            req: ReadSongData;
            res: {
                /**
                 * OK
                 */
                '200': Song;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
        delete: {
            req: DeleteSongData;
            res: {
                /**
                 * OK
                 */
                '200': unknown;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/songs/{id}/recommendations': {
        get: {
            req: RecommendationsBasedOnSongData;
            res: {
                /**
                 * OK
                 */
                '200': Array<Song>;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/songs/genre/{id}': {
        get: {
            req: ReadSongsOfGenreData;
            res: {
                /**
                 * OK
                 */
                '200': Array<Song>;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/songs/artist/{id}': {
        get: {
            req: ReadSongsOfArtistData;
            res: {
                /**
                 * OK
                 */
                '200': Array<Song>;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/genres/{id}': {
        get: {
            req: ReadGenreData;
            res: {
                /**
                 * OK
                 */
                '200': Genre;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
        delete: {
            req: DeleteGenreData;
            res: {
                /**
                 * OK
                 */
                '200': unknown;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/artists/{id}': {
        get: {
            req: ReadArtistData;
            res: {
                /**
                 * OK
                 */
                '200': Artist;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/albums/{id}': {
        get: {
            req: ReadAlbumData;
            res: {
                /**
                 * OK
                 */
                '200': Album;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/artist/{id}': {
        delete: {
            req: DeleteSong1Data;
            res: {
                /**
                 * OK
                 */
                '200': unknown;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
    '/album/{id}': {
        delete: {
            req: DeleteAlbumData;
            res: {
                /**
                 * OK
                 */
                '200': unknown;
                /**
                 * Not Found
                 */
                '404': string;
            };
        };
    };
};